import = ["/Users/xlong/.config/alacritty/dracula.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 22.0
# size = 18.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[selection]
save_to_clipboard = true

[window]
decorations = "full"
dynamic_padding = true

[window.dimensions]
columns = 100
lines = 25
