format = """
[#](blue) \
$username\
$hostname\
$directory\
$git_branch\
$git_status\
${custom.python_venv_only}\
$time\
$line_break\
$character\
"""

# User
[username]
style_user = 'cyan bold'
style_root = 'red bold'
disabled = false
show_always = true
format = "[$user]($style) "

# Hostname (Machine name)
[hostname]
ssh_only = false
format = "@ [$hostname](green) "

# Directory
[directory]
style = "bold yellow"
home_symbol = "~"
format = "in [$path]($style) "

# Git Branch
[git_branch]
style = "cyan"
format = "[$branch]($style)"

# Git Status
[git_status]
format = '([\[$all_status$ahead_behind\]]($style)) '

[custom.python_venv_only]
description = "Show Python info only when a venv is active"
command = '''
    python_version=$(python --version 2>&1 | awk "{print \$2}")
    venv_name=$(basename "$VIRTUAL_ENV")
    echo " v$python_version($venv_name)"
'''
when = '[[ -n "$VIRTUAL_ENV" ]]'
format = "[$output]($style) "
style = "bold yellow"

[time]
disabled = false
format = '[\[$time\]](white)'
time_format = '%T'

# Character ($)
[character]
success_symbol = "[\\$](red)"
error_symbol = "[\\$](bold red)"
